### ISSUE TITLE
Snapshot without key/tag defined

### ISSUE THREAD

**Issue by indreshcha** [miztiik/serverless-janitor-ebs-snapshots#2]
Hi,
How can we delete the snapshots  which are created by manually AND don't have tag defined  if we are using aws life cycle manager and it keeping the snapshot as per defined rule  in that case how  we can customize snapshot deletion ?  * we have some screenshot created by users manually and some we are creating daily on the basis of life cycle manager.  so how we can achieve customize deletion of snapshot not mentioned in life cyle manager  .Need to define retention days as per staging area (qa,prod,test) it should not overlapped with existing life cycle manager policy.

**Comment by miztiik** [comment]
The basic premise of this function is to clean up ebs snapshots which have the _needle_ tags, that can identify the ones to be deleted from the list of all snapshots(haystack).

If you are expecting different behaviour, then it will have to be custom written.

Closing it as not an issue.
